STORAGE-TYPE: "JSON" #MONGO,JSON,REDIS

SETTINGS:
  SCOREBOARD-ENABLED: true
  NAMETAG-HEAL: true
  SCENARIOS: false
  SERVER-TYPE: SINGLE #Single,Multiple

LOBBY:
  WORLD: "Lobby"

TABLIST:
  ENABLED: True
  # Use \n for new line
  HEADER: "&7&m--------------------\n&fWelcome to &bBurrito&f!\n&7&m--------------------"
  FOOTER: "&7&m--------------------\n&fwww.server.com\n&7&m--------------------"

GAME:
  # Seconds
  ENDERPEARL:
    COOLDOWN: 16
    MESSAGE: "&eYou are now on enderpearl cooldown for 16 seconds."
    ON_COOLDOWN_MESSAGE: "&cYou are still on cooldown for &c&l<remaining> seconds&r&c."

  PLAYERS:
    MIN: 3
    MAX: 10
  BORDER:
    INITIAL: 125
    REDUCTION: 25
    MINIMAL: 25
    TIME: 120 #In seconds

GENERATION:
  TYPE: INTEGRATED #INTEGRATED, SEED
  #Integrated
  LIQUID_LIMIT:
    WATER: 3000
    LAVA: 500
  #Only if option is false
  REPLACEMENTS: #https://gist.github.com/NonUKry/f4d852b13b0734dc4b8557370a3a1594
    - "=Desert"
    - "=Plains"
    - "Forest->Plains"
    - "Deep Ocean->Plains"
    - "Ocean->Plains"
    - "Jungle->Desert"
    - "Ice Plains->Desert"
    - "JungleEdge->Forest"
    - "JungleHills->Forest"
    - "Cold Taiga->Plains"
    - "Ice Mountains->Plains"
    - "FrozenRiver->Plains"
    - "OTHERS->Plains"
  #Seed
  SEED-LIST: []
